_prefs: 
  mapid: ''
  saveCenter: false
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 28.9119
  - 41.0607
  - 10
description: ''
format: "png8:m=h:c=128"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Wheatpaste
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6"
styles: 
  - style.mss
  - terrain.mss
  - label.mss
template: ''
